### ISSUE TITLE
Which one is the actual site?

### ISSUE THREAD

**Issue by alexgleason** [occupywallst/occupywallst.org#1]
I'm confused; the site footer links to [a Django project](https://github.com/jart/occupywallst), and this one looks like a Jekyll site (with no readme)? Just curious. :smile:

Thanks

**Comment by jart** [comment]
We were working on migrating the website so its content would be fully tracked by GitHub. That way anyone could easily contribute using GitHub's web editing features. But the project was abandoned.

**Comment by alexgleason** [comment]
Ahh, that's a shame; seems like a nice idea. Thanks for working on this.
